"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type CubeRow = { year:number; provider_state:string; provider_specialty:string; drug_class:string; marketed_name_type:string; volume_decile:number; total_claims:number; total_30day_fills:number; total_drug_cost:number; prescribers:number; selected_class_fills:number };
type CubeDimensions = { provider_state:string[]; provider_specialty:string[]; drug_class:string[]; marketed_name_type:string[] };
type ProductRow = { year:number; drug_class:string; brand_name:string; generic_name:string; marketed_name_type:string; total_30day_fills:number; total_drug_cost:number; cost_per_fill:number; prescribers:number };
type OpportunityRow = { provider_state:string; rank_primary:number; score_primary:number; total_30day_fills:number; growth_2022_2024_cagr:number; selected_class_share:number; peer_gap_pp:number; rank_range:number };
type ConcentrationRow = { year:number; top_1_share:number; top_5_share:number; top_10_share:number; top_20_share:number; gini:number; hhi:number };
type LorenzPoint = { year:number; provider_pct:number; fill_pct:number };
type DashboardData = { meta:{scope_note:string}; cube:CubeRow[]; market_year:unknown[]; class_year:unknown[]; product_year:ProductRow[]; state_year:unknown[]; specialty_year:unknown[]; city_year:unknown[]; state_opportunity:OpportunityRow[]; specialty_opportunity:unknown[]; concentration:ConcentrationRow[]; lorenz:LorenzPoint[]; product_scatter:ProductRow[]; opportunity_weights:Record<string,Record<string,number>>; limitations:string[] };
type DashboardWire = Omit<DashboardData,"cube"> & { cube:number[][]; cube_dimensions:CubeDimensions };
type Filters = { year:string; state:string; specialty:string; drugClass:string; nameType:string; decile:string };

const initialFilters:Filters={year:"2024",state:"All",specialty:"All",drugClass:"All",nameType:"All",decile:"All"};
const compact=new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1});
const money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1});
const pct=(value:number|null|undefined,digits=1)=>value==null||!Number.isFinite(value)?"—":`${(value*100).toFixed(digits)}%`;
const sum=(rows:CubeRow[])=>rows.reduce((a,r)=>({claims:a.claims+r.total_claims,fills:a.fills+r.total_30day_fills,cost:a.cost+r.total_drug_cost,selected:a.selected+r.selected_class_fills}),{claims:0,fills:0,cost:0,selected:0});

function BarList({rows,valueKey,labelKey,accent=false}:{rows:Array<Record<string,string|number>>;valueKey:string;labelKey:string;accent?:boolean}){
  const max=Math.max(...rows.map(r=>Number(r[valueKey])||0),1);
  return <div className="bar-list">{rows.map((r,i)=><div className="bar-row" key={`${r[labelKey]}-${i}`}><div className="bar-label"><span>{r[labelKey]}</span><strong>{compact.format(Number(r[valueKey])||0)}</strong></div><div className="bar-track"><span className={accent?"accent-bar":""} style={{width:`${Math.max(2,(Number(r[valueKey])||0)/max*100)}%`}}/></div></div>)}</div>;
}

function LorenzCanvas({points}:{points:LorenzPoint[]}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const c=ref.current;if(!c||!points.length)return;const d=window.devicePixelRatio||1,w=c.clientWidth,h=230;c.width=w*d;c.height=h*d;const x=c.getContext("2d");if(!x)return;x.scale(d,d);x.clearRect(0,0,w,h);const p=28;x.strokeStyle="#d5d9d2";x.lineWidth=1;x.beginPath();x.moveTo(p,h-p);x.lineTo(w-p,p);x.stroke();x.strokeStyle="#0d7f66";x.lineWidth=3;x.beginPath();points.forEach((v,i)=>{const px=p+(w-2*p)*v.provider_pct/100,py=h-p-(h-2*p)*v.fill_pct/100;if(i)x.lineTo(px,py);else x.moveTo(px,py)});x.stroke();x.fillStyle="#667069";x.font="11px system-ui";x.fillText("0% providers",p,h-8);x.fillText("100%",w-p-30,h-8);x.save();x.translate(10,h/2+28);x.rotate(-Math.PI/2);x.fillText("Cumulative fills",0,0);x.restore()},[points]);
  return <canvas ref={ref} className="canvas-chart" aria-label="Lorenz curve of prescriber standardized fills"/>;
}

function ScatterCanvas({rows}:{rows:ProductRow[]}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const c=ref.current;if(!c||!rows.length)return;const d=window.devicePixelRatio||1,w=c.clientWidth,h=250;c.width=w*d;c.height=h*d;const x=c.getContext("2d");if(!x)return;x.scale(d,d);x.clearRect(0,0,w,h);const p=32,xs=rows.map(r=>Math.log10(Math.max(r.total_30day_fills,1))),ys=rows.map(r=>Math.log10(Math.max(r.cost_per_fill,.01))),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);x.strokeStyle="#e3e6e0";x.beginPath();x.moveTo(p,8);x.lineTo(p,h-p);x.lineTo(w-8,h-p);x.stroke();rows.forEach((r,i)=>{const px=p+(w-p-16)*(xs[i]-minX)/Math.max(maxX-minX,.01),py=h-p-(h-p-16)*(ys[i]-minY)/Math.max(maxY-minY,.01);x.fillStyle=r.drug_class.includes("GLP-1")?"#ef7d4f":"#0d7f66";x.globalAlpha=.72;x.beginPath();x.arc(px,py,Math.min(9,3+Math.sqrt(r.prescribers)/18),0,Math.PI*2);x.fill()});x.globalAlpha=1;x.fillStyle="#667069";x.font="11px system-ui";x.fillText("Standardized fills →",w-116,h-9);x.save();x.translate(10,126);x.rotate(-Math.PI/2);x.fillText("Cost per fill →",0,0);x.restore()},[rows]);
  return <canvas ref={ref} className="canvas-chart" aria-label="National product cost versus standardized fill scatter plot"/>;
}

export function Dashboard(){
  const [data,setData]=useState<DashboardData|null>(null),[error,setError]=useState(""),[filters,setFilters]=useState<Filters>(initialFilters),[search,setSearch]=useState(""),[modal,setModal]=useState(false);
  useEffect(()=>{fetch("/dashboard_data.json").then(r=>{if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json() as Promise<DashboardWire>}).then(raw=>{const d=raw.cube_dimensions;const cube:CubeRow[]=raw.cube.map(r=>({year:r[0],provider_state:d.provider_state[r[1]],provider_specialty:d.provider_specialty[r[2]],drug_class:d.drug_class[r[3]],marketed_name_type:d.marketed_name_type[r[4]],volume_decile:r[5],total_claims:r[6],total_30day_fills:r[7],total_drug_cost:r[8],prescribers:r[9],selected_class_fills:r[10]}));setData({...raw,cube})}).catch(e=>setError(String(e)))},[]);
  useEffect(()=>{const h=(e:KeyboardEvent)=>{if(e.key==="Escape")setModal(false)};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h)},[]);
  const options=useMemo(()=>data?{states:[...new Set(data.cube.map(r=>r.provider_state))].sort(),specialties:[...new Set(data.cube.map(r=>r.provider_specialty))].sort(),classes:[...new Set(data.cube.map(r=>r.drug_class))].sort(),names:[...new Set(data.cube.map(r=>r.marketed_name_type))].sort()}:null,[data]);
  const matches=useCallback((r:CubeRow,includeYear=true)=>(!includeYear||r.year===Number(filters.year))&&(filters.state==="All"||r.provider_state===filters.state)&&(filters.specialty==="All"||r.provider_specialty===filters.specialty)&&(filters.drugClass==="All"||r.drug_class===filters.drugClass)&&(filters.nameType==="All"||r.marketed_name_type===filters.nameType)&&(filters.decile==="All"||r.volume_decile===Number(filters.decile)),[filters]);
  const view=useMemo(()=>data?.cube.filter(r=>matches(r))||[],[data,matches]);
  const totals=useMemo(()=>sum(view),[view]);
  const previous=useMemo(()=>data?sum(data.cube.filter(r=>r.year===Number(filters.year)-1&&matches(r,false))):null,[data,filters.year,matches]);
  const yoy=previous&&previous.fills?totals.fills/previous.fills-1:null;
  const classRows=useMemo(()=>{if(!data)return[];const m=new Map<string,number>();data.cube.filter(r=>r.year===Number(filters.year)&&(filters.state==="All"||r.provider_state===filters.state)&&(filters.specialty==="All"||r.provider_specialty===filters.specialty)&&(filters.nameType==="All"||r.marketed_name_type===filters.nameType)&&(filters.decile==="All"||r.volume_decile===Number(filters.decile))).forEach(r=>m.set(r.drug_class,(m.get(r.drug_class)||0)+r.total_30day_fills));return[...m].map(([drug_class,total_30day_fills])=>({drug_class,total_30day_fills})).sort((a,b)=>b.total_30day_fills-a.total_30day_fills).slice(0,8)},[data,filters]);
  const stateRows=useMemo(()=>{const m=new Map<string,number>();view.forEach(r=>m.set(r.provider_state,(m.get(r.provider_state)||0)+r.total_30day_fills));return[...m].map(([provider_state,total_30day_fills])=>({provider_state,total_30day_fills})).sort((a,b)=>b.total_30day_fills-a.total_30day_fills).slice(0,10)},[view]);
  const specialtyRows=useMemo(()=>{const m=new Map<string,number>();view.forEach(r=>m.set(r.provider_specialty,(m.get(r.provider_specialty)||0)+r.total_30day_fills));return[...m].map(([provider_specialty,total_30day_fills])=>({provider_specialty,total_30day_fills})).sort((a,b)=>b.total_30day_fills-a.total_30day_fills).slice(0,8)},[view]);
  const trendRows=useMemo(()=>data?[2022,2023,2024].map(year=>({year,total_30day_fills:sum(data.cube.filter(r=>r.year===year&&matches(r,false))).fills})):[],[data,matches]);
  const products=useMemo(()=>data?.product_year.filter(r=>r.year===Number(filters.year)&&(filters.drugClass==="All"||r.drug_class===filters.drugClass)&&(filters.nameType==="All"||r.marketed_name_type===filters.nameType)).slice(0,10)||[],[data,filters.year,filters.drugClass,filters.nameType]);
  const opportunities=useMemo(()=>data?.state_opportunity.filter(r=>r.provider_state.toLowerCase().includes(search.toLowerCase())).slice(0,20)||[],[data,search]);
  const opportunityCsv=useMemo(()=>{const head=["rank","state","score","fills","cagr","selected_class_share","gap_pp","rank_range"],body=opportunities.map(r=>[r.rank_primary,r.provider_state,r.score_primary,r.total_30day_fills,r.growth_2022_2024_cagr,r.selected_class_share,r.peer_gap_pp,r.rank_range].join(","));return `data:text/csv;charset=utf-8,${encodeURIComponent([head.join(","),...body].join("\n"))}`},[opportunities]);
  const concentration=data?.concentration.find(r=>r.year===Number(filters.year)),lorenz=data?.lorenz.filter(r=>r.year===Number(filters.year))||[],scatter=data?.product_scatter.filter(r=>filters.drugClass==="All"||r.drug_class===filters.drugClass)||[];
  const update=(key:keyof Filters,value:string)=>setFilters(c=>({...c,[key]:value}));
  if(error)return <main className="center-state"><div><span className="eyebrow">Dashboard unavailable</span><h1>Could not load validated data</h1><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></div></main>;
  if(!data)return <main className="center-state"><div className="loader"/><p>Loading validated CMS market data…</p></main>;
  return <main>
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">Rx</span><span>MarketIQ<small>Medicare Part D intelligence</small></span></a><div className="header-actions"><span className="data-badge"><i/>CMS · 2022–2024</span><button className="ghost" onClick={()=>setModal(true)}>Methodology & limitations</button></div></header>
    <section className="hero" id="top"><div><span className="eyebrow">Real-world pharmaceutical market analytics</span><h1>Where is the observed<br/><em>diabetes market</em> moving?</h1><p>Explore Medicare Part D utilization, cost, product mix, prescriber concentration, and transparent market-development scenarios.</p></div><div className="hero-note"><span>Latest complete year</span><strong>2024</strong><p>Official CMS provider × drug records<br/>Source modified May 21, 2026</p></div></section>
    <section className="filters" aria-label="Dashboard filters">
      <label><span>Year</span><select value={filters.year} onChange={e=>update("year",e.target.value)}>{[2024,2023,2022].map(v=><option key={v}>{v}</option>)}</select></label>
      <label><span>State</span><select value={filters.state} onChange={e=>update("state",e.target.value)}><option>All</option>{options?.states.map(v=><option key={v}>{v}</option>)}</select></label>
      <label><span>Specialty</span><select value={filters.specialty} onChange={e=>update("specialty",e.target.value)}><option>All</option>{options?.specialties.map(v=><option key={v}>{v}</option>)}</select></label>
      <label><span>Drug class</span><select value={filters.drugClass} onChange={e=>update("drugClass",e.target.value)}><option>All</option>{options?.classes.map(v=><option key={v}>{v}</option>)}</select></label>
      <label><span>Name type</span><select value={filters.nameType} onChange={e=>update("nameType",e.target.value)}><option>All</option>{options?.names.map(v=><option key={v}>{v}</option>)}</select></label>
      <label><span>Provider decile</span><select value={filters.decile} onChange={e=>update("decile",e.target.value)}><option>All</option>{[1,2,3,4,5,6,7,8,9,10].map(v=><option key={v} value={v}>D{v}{v===1?" · highest volume":""}</option>)}</select></label><button className="reset" onClick={()=>setFilters(initialFilters)}>Reset</button>
    </section>
    {!view.length?<section className="empty"><span>0 matching segments</span><h2>No observed CMS rows match this filter combination.</h2><p>CMS suppression and sparse combinations can produce empty states. Broaden one or more filters.</p><button onClick={()=>setFilters(initialFilters)}>Reset filters</button></section>:<>
      <section className="kpi-grid"><article><span>Standardized 30-day fills</span><strong>{compact.format(totals.fills)}</strong><small>{yoy==null?"No comparable prior year":`${yoy>=0?"↑":"↓"} ${pct(Math.abs(yoy))} vs prior year`}</small></article><article><span>Part D claims</span><strong>{compact.format(totals.claims)}</strong><small>Original fills + refills</small></article><article><span>Aggregate drug cost</span><strong>{money.format(totals.cost)}</strong><small>{money.format(totals.cost/Math.max(totals.fills,1))} per standardized fill</small></article><article className="accent-card"><span>Selected-class fill share</span><strong>{pct(totals.selected/Math.max(totals.fills,1))}</strong><small>GLP-1-based therapies</small></article></section>
      <section className="grid two-one"><article className="panel"><div className="panel-head"><div><span className="eyebrow">Market evolution</span><h2>Three-year standardized-fill trend</h2></div><span className="panel-chip">Filtered view</span></div><div className="trend">{trendRows.map((r,i)=><div key={r.year} className="trend-col"><div className="trend-value">{compact.format(r.total_30day_fills)}</div><div className="trend-bar" style={{height:`${40+110*r.total_30day_fills/Math.max(...trendRows.map(x=>x.total_30day_fills),1)}px`}}/><b>{r.year}</b>{i>0&&trendRows[i-1].total_30day_fills>0?<small>{pct(r.total_30day_fills/trendRows[i-1].total_30day_fills-1)}</small>:<small>baseline</small>}</div>)}</div></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">Therapeutic mix</span><h2>Class leaders</h2></div></div><BarList rows={classRows} valueKey="total_30day_fills" labelKey="drug_class" accent/></article></section>
      <section className="grid equal"><article className="panel"><div className="panel-head"><div><span className="eyebrow">National product view</span><h2>Leading brands / labels</h2></div><span className="panel-chip">{filters.year}</span></div><div className="product-table">{products.map((p,i)=><div key={`${p.brand_name}-${i}`}><span className="rank">{String(i+1).padStart(2,"0")}</span><div><strong>{p.brand_name}</strong><small>{p.generic_name} · {p.drug_class}</small></div><div className="right"><b>{compact.format(p.total_30day_fills)}</b><small>{money.format(p.total_drug_cost)}</small></div></div>)}</div></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">National product economics</span><h2>Cost vs. standardized fills</h2></div><div className="legend"><i/><span>Other</span><i className="orange"/><span>GLP-1</span></div></div><ScatterCanvas rows={scatter}/><p className="footnote">Log-scaled axes. Bubble size reflects prescriber count; descriptive costs are not net prices.</p></article></section>
      <section className="grid equal"><article className="panel"><div className="panel-head"><div><span className="eyebrow">Geographic scale</span><h2>Leading states by fills</h2></div></div><BarList rows={stateRows} valueKey="total_30day_fills" labelKey="provider_state"/></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">Prescriber mix</span><h2>Specialty contribution</h2></div></div><BarList rows={specialtyRows} valueKey="total_30day_fills" labelKey="provider_specialty" accent/></article></section>
      <section className="grid concentration-grid"><article className="panel stat-panel"><div><span className="eyebrow">Concentration</span><h2>Who drives observed volume?</h2><p>National provider-level standardized fills for {filters.year}.</p></div><div className="mini-stats"><div><strong>{pct(concentration?.top_1_share)}</strong><span>Top 1% share</span></div><div><strong>{pct(concentration?.top_10_share)}</strong><span>Top 10% share</span></div><div><strong>{concentration?.gini.toFixed(3)}</strong><span>Gini coefficient</span></div><div><strong>{concentration?.hhi.toFixed(5)}</strong><span>HHI (0–1)</span></div></div></article><article className="panel"><div className="panel-head"><div><span className="eyebrow">Lorenz curve</span><h2>Prescriber inequality</h2></div><span className="panel-chip">National</span></div><LorenzCanvas points={lorenz}/><p className="footnote">Equality line in gray; observed cumulative fill distribution in green.</p></article></section>
      <section className="panel opportunity"><div className="panel-head opportunity-head"><div><span className="eyebrow">Explainable opportunity scenario</span><h2>State market-development hypotheses</h2><p>Scale 35% · growth 25% · selected-class gap 25% · completeness 15%</p></div><div className="table-actions"><label><span className="sr-only">Search states</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search state…"/></label><a href={opportunityCsv} download="rxmarketiq_state_opportunities.csv">Download CSV</a></div></div><div className="opportunity-table" role="table"><div className="table-header" role="row"><span>Rank / state</span><span>Score</span><span>2024 fills</span><span>2022–24 CAGR</span><span>GLP-1 share</span><span>Gap vs national</span><span>Rank sensitivity</span></div>{opportunities.map(r=><div className="table-row" role="row" key={r.provider_state}><span><b>#{r.rank_primary}</b><strong>{r.provider_state}</strong></span><span><em style={{width:`${r.score_primary}%`}}/>{r.score_primary.toFixed(1)}</span><span>{compact.format(r.total_30day_fills)}</span><span>{pct(r.growth_2022_2024_cagr)}</span><span>{pct(r.selected_class_share)}</span><span>{r.peer_gap_pp.toFixed(1)} pp</span><span>±{r.rank_range} ranks</span></div>)}</div><p className="responsible-note"><strong>Responsible use:</strong> A high score is a prompt for aggregated market research. It is not evidence of unmet clinical need, provider quality, promotional causation, or an instruction to target a person.</p></section>
    </>}
    <section className="limitations"><div><span className="eyebrow">Interpretation guardrails</span><h2>What this data can—and cannot—say</h2></div><ul>{data.limitations.slice(0,4).map(i=><li key={i}>{i}</li>)}</ul><button className="ghost" onClick={()=>setModal(true)}>Read all methods & limitations</button></section>
    <footer><div className="brand"><span className="brand-mark">Rx</span><span>MarketIQ<small>Portfolio analytics project</small></span></div><p>Source: CMS Medicare Part D Prescribers — by Provider and Drug · 2022–2024<br/>Public provider information used at aggregated grain; beneficiary identity is not present.</p><a href="https://data.cms.gov/provider-summary-by-type-of-service/medicare-part-d-prescribers/medicare-part-d-prescribers-by-provider-and-drug" target="_blank" rel="noreferrer">Official CMS source ↗</a></footer>
    {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(false)}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="method-title"><button className="modal-close" onClick={()=>setModal(false)} aria-label="Close methodology dialog">×</button><span className="eyebrow">Methodology & limitations</span><h2 id="method-title">How to read RxMarketIQ</h2><h3>Scope</h3><p>{data.meta.scope_note} Insulin may include uses outside Type 2 diabetes because diagnosis/indication is absent.</p><h3>Metric definitions</h3><p>Claims include original fills and refills. Standardized fills reflect days supplied divided by 30 using CMS methodology. Aggregate cost combines payer and beneficiary amounts and is not CMS payment or net price.</p><h3>Opportunity score</h3><p>The primary score ranks state percentiles for log market scale (35%), winsorized 2022–2024 CAGR (25%), positive gap below national GLP-1-based fill share (25%), and beneficiary-count completeness (15%). Growth-led and gap-led scenarios produce the rank-sensitivity range.</p><h3>All limitations</h3><ul>{data.limitations.map(i=><li key={i}>{i}</li>)}</ul><div className="modal-source"><span>Official source</span><a href="https://data.cms.gov/provider-summary-by-type-of-service/medicare-part-d-prescribers/medicare-part-d-prescribers-by-provider-and-drug" target="_blank" rel="noreferrer">CMS Medicare Part D Prescribers ↗</a></div></section></div>}
  </main>;
}
